export const CHANGE_SEARCH_FIELD =  'CHANGE_SEARCH_FIELD ';

export const REQUEST_ROOTS_PENDING = 'REQUEST_ROOTS_PENDING';
export const REQUEST_ROOTS_SUCCESS = 'REQUEST_ROOTS_SUCCESS';
export const REQUEST_ROOTS_FAILED = 'REQUEST_ROOTS_FAILED';

